"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 27;
let altura = 1.80;
const nacionalidade = 'brasileira';
const colegas = ['luis', 'paulo'];
const tecnologias = ['html', 'css', 'js'];
const notas = [3, 4, 5, 6];
const lista = ['luis', true, 25];
let idadeDaAna = 25;
idadeDaAna = "25 anos";
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
